services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole              
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: "Pacific/Tahiti"           
      WEBPASSWORD: "password"      # to change
      ServerIP: "192.XXX.XXX.XXX"  # IP of the raspberry Pi (not the network address)
      DNSMASQ_LISTENING: "all"
      DNS1: "1.1.1.1"
      DNS2: "1.0.0.1"      
    cap_add:
     - NET_ADMIN
    volumes:
      - pihole_etc-pihole:/etc/pihole
      - pihole_etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped

volumes:
  pihole_etc-pihole:
    external: true
  pihole_etc-dnsmasq.d:
    external: true
